
name: Build CI

on:
  push:
    branches: [ master ]

jobs:
  gradle:
    name: Gradle CI Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Clone repository

    - name: clone latest QNotified
      run: 
        git clone -b master https://github.com/ferredoxin/QNotified.git ~/QN &&
        ls &&
        mv -f ~/CardMsgList.kt ~/QN/app/src/main/java/me/singleneuron/base/bridge/CardMsgList.kt &&
        cd ~/QN
        
    - name: Prepare Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        java-package: jdk+fx

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/QN/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle

    - name: Build project
      run: |
        if ${{ !!github.head_ref }}; then echo "::warning:: Gradle $WARN_ON_PR"; fi
        gradle wrapper
        bash gradlew build
    
    - name: Upload articact
      uses: actions/upload-artifact@v2
      if: ${{ !github.head_ref }}
      with:
        path: app/build/outputs/apk
        name: QN-Card
